// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using UnityEditor;
using System.Collections;

public class ScriptedObjectMonitorWindow : EditorWindow 
{
	static ScriptedObjectMonitor monitor;

	// Add menu item named "My Window" to the Window menu
	[MenuItem("Window/Scripted Object Monitor")]
	public static void ShowWindow()
	{
		//Show existing window instance. If one doesn't exist, make one.
		EditorWindow.GetWindow(typeof(ScriptedObjectMonitorWindow));

		// attach to scripted object monitor
		monitor = ScriptedObjectMonitor.GetInstance();
	}

	public void OnGUI()
	{
		if ( monitor )
		{
			monitor.UseWindowWidth(Screen.width);
			monitor.Display();
			Repaint ();
		}
	}
}


